/*
 *    Copyright (c) 2018-2025, lengleng All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * Neither the name of the pig4cloud.com developer nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * Author: lengleng (wangiegie@gmail.com)
 */

export const tableOption = {
    index: true,
    selection: true,
    indexLabel: '序号',
    menuAlign: 'center',
    editBtn: false,
    delBtn: false,
    viewBtn: true,
    menu: true,
    align: 'center',
    addBtn: false,
    refreshBtn: false,
    columnBtn: false,
    menuWidth: "180",
    height: "400",
    labelWidth: "120",
    dialogWidth: "80%",
    dialogHeight: "80%",
    dialogClickModal: false,
    column: [
        {
            label: "供应商", //0
            prop: "suppliername",
            editDisplay: false,//编辑禁止显示
            addDisplay: false,//新增禁止显示
            addDisabled: true,//新增禁止输入
            editDisabled: true,//编辑禁止输入
            placeholder: "系统生成",
            // hide: true,
            span: 8
        },
        {
            label: "供应商代码",
            prop: "suppliercode",
            span: 8,
            // width: 150,
            // hide: true,
            editDisplay: true,//编辑禁止显示
            addDisplay: false,//新增禁止显示
            addDisabled: true,//新增禁止输入
            editDisabled: true,//编辑禁止输入
            viewDisplay: true,
            viewDisabled: true,
        },
        {
            label: "供货商",  //1
            prop: "vendorname",
            // type: "select",
            editDisabled: true,
            editDisplay: false,
            addDisplay: true,
            viewDisplay: false,
            viewDisabled: true,
            multiple: false,
            // rules: [{
            //     required: true,
            //     message: '联营商名称不能为空',
            //     trigger: 'blur'
            // }],
            // props: {
            //     label: "name",
            //     value: "id",
            // },
            // props: {
            //     api: "querySuppliernameData02@retail.sys.comSelect",
            //     radio: true,//true为单选，false为多选
            // },
            // component: "DroplistControl",
            span: 8

        },
        {
            label: "款号",  //2
            prop: "itemno",
            editDisabled: false,
            addDisplay: true,
            overHidden: true,
            width: 120,
            span: 8,
            rules: [{
                required: true,
                message: 'appKey不能为空',
                trigger: 'blur'
            }],
        },
        {
            label: "货号", //3
            prop: "huohao",
            editDisabled: false,
            addDisplay: true,
            overHidden: true,
            span: 8,
            rules: [{
                required: true,
                message: 'appSecret不能为空',
                trigger: 'blur'
            }],
        },
        {
            label: "颜色规格", //4
            prop: "colorGuige",
            // type: "select",
            // multiple: true,
            editDisabled: false,
            addDisplay: true,
            // rules: [{
            //     required: true,
            //     message: 'accessToken不能为空',
            //     trigger: 'blur'
            // }],
            // width: 300,
            span: 8
        },
        {
            label: "商品编码(外部码)",
            prop: "goodscode",
            span: 8,
            width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "商品名称",
            prop: "goodsname",
            // type: "date",
            span: 8,
            width: 120,
            // format: "yyyy-MM-dd",
            // valueFormat: "yyyy-MM-dd",
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            addDisabled: true,
        },
        {
            label: "市场价",
            prop: "price",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            addDisabled: true,
        },
        {
            label: "到手价",
            prop: "daoshouprice",
            // type: "date",
            span: 8,
            // width: 120,
            // format: "yyyy-MM-dd",
            // valueFormat: "yyyy-MM-dd",
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            addDisabled: true,
        },
        {
            label: "首销日",
            prop: "firstsalesday",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "累计销售数量",
            prop: "sumsalesqty",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "累计退货数量",
            prop: "sumrefundqty",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "累计退货率",
            prop: "sumrefundratio",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "实时库存",
            prop: "stock",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "周转天数",
            prop: "turnoverdays",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "补货建议",
            prop: "buhuojianyi",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "要求到仓日期",
            prop: "yaoqiudaocangdate",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "要求到仓数量",
            prop: "yaoqiudaocangqty",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数前6天销售数量",
            prop: "salesqtydsyneg6",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数前5天销售数量",
            prop: "salesqtydsyneg5",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数前4天销售数量",
            prop: "salesqtydsyneg4",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数前3天销售数量",
            prop: "salesqtydsyneg3",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数前2天销售数量",
            prop: "salesqtydsyneg2",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数前1天销售数量",
            prop: "salesqtydsyneg1",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数当天销售数量",
            prop: "salesqtydsy0",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "最近7天销售",
            prop: "salesqtyday7sum",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "截数当月销售数据",
            prop: "salescurrentmon",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "1月销售数量",
            prop: "salesmon1",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "2月销售数量",
            prop: "salesmon2",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "3月销售数量",
            prop: "salesmon3",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "4月销售数量",
            prop: "salesmon4",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "5月销售数量",
            prop: "salesmon5",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "6月销售数量",
            prop: "salesmon6",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "7月销售数量",
            prop: "salesmon7",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "8月销售数量",
            prop: "salesmon8",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "9月销售数量",
            prop: "salesmon9",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "10月销售数量",
            prop: "salesmon10",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "11月销售数量",
            prop: "salesmon11",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "12月销售数量",
            prop: "salesmon12",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "1月退货数量",
            prop: "refund1",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "2月退货数量",
            prop: "refund2",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "3月退货数量",
            prop: "refund3",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "4月退货数量",
            prop: "refund4",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "5月退货数量",
            prop: "refund5",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "6月退货数量",
            prop: "refund6",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "7月退货数量",
            prop: "refund7",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "8月退货数量",
            prop: "refund8",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "9月退货数量",
            prop: "refund9",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "10月退货数量",
            prop: "refund10",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "11月退货数量",
            prop: "refund11",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "12月退货数量",
            prop: "refund12",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "店铺",
            prop: "locId",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "按21天可销售推断库存缺口",
            prop: "yaoqiudaocangqtyremark",
            span: 8,
            // width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "销售截数日期",
            prop: "SalesDeadlineDate",
            span: 8,
            width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "供货商代码",
            prop: "vendorcode",
            span: 8,
            width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "补货建议代码",
            prop: "buhuojianyicode",
            span: 8,
            width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "库存缺口代码",
            prop: "kucunquekoucode",
            span: 8,
            width: 120,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },
        {
            label: "图片链接",
            prop: "pictureaddr",
            span: 8,
            width: 300,
            addDisplay: true,
            editDisplay: true,
            editDisabled: true,
            visible: false,
            addDisabled: true,
        },

    ],
}



export const fOption = {
    submitBtn: false,
    emptyBtn: false,
    dialogClickModal: false,
    labelWidth: "150",
    column: [
        {
            label: "公司",
            prop: "CmpKey",
            span: 7,
            type: "select",
            dicData: [],
            props: {
                label: 'name',
                value: 'id'
            },
            // dicUrl: 'http://127.0.0.1:9003/po1mnt007/queryCmpKey',
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择公司",
                    radio: false,
                    checkall: false,
                },
            ],
        },
        {
            label: "供应商",
            prop: "SupplierCode",
            type: "select",
            dicData: [],
            multiple: true, //多选
            props: {
                label: "name",
                value: "id",
            },
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择供应商",
                    radio: false,
                    checkall: false,
                },
            ],
            span: 7
        },
        {
            prop: "VendorCode",
            label: "供货商",
            // labelWidth: 100,
            type: "select",
            multiple: true,
            dicData: [],
            props: {
                label: "name",
                value: "id",
            },
            collapseTags: true,     // 折叠
            maxCollapseTags: 1,     // 最大显示数量
            collapseTagsTooltip: true,  // 折叠显示
            // props: {
            //     radio: true,
            //     checkall: true
            // },
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择供货商",
                    radio: true,
                    checkall: true
                },
            ],
            // props: {
            //     api: "queryVendorList@retail.po1.po1mnt007",
            //     checkall: true,
            //     watch: true,
            //     // params: {
            //     //     userid: this.SupplierCode,
            //     // },

            // },
            // component: "DroplistControl",
            clearable: true,
            span: 7,
        },
        {
            label: "网店",
            prop: "ShopCode",
            type: "select",
            dicData: [],
            multiple: true, //多选
            props: {
                label: "name",
                value: "id",
            },
            collapseTags: true, // 折叠
            maxCollapseTags: 1, // 最大显示数量
            collapseTagsTooltip: true,  // 折叠显示
            // props: {
            //     api: "querySuppliernameData02@retail.sys.comSelect",
            //     radio: false,
            // },
            // component: "DroplistControl",
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择网店",
                    radio: false,
                    checkall: false,
                },
            ],
            span: 7
        },
        {
            label: "销售截数日期",
            prop: "SalesDeadlineDate",
            type: "datetime",
            format: "YYYY-MM-DD",
            valueFormat: "YYYY-MM-DD",
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择销售截数日期",
                },
            ],
            span: 7
        },
        {
            label: "累计开始日期",
            prop: "QueryDate1",
            type: "datetime",
            format: "YYYY-MM-DD",
            valueFormat: "YYYY-MM-DD",
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择累计开始日期",
                },
            ],
            span: 7
        },
        {
            label: "累计实际开始日期",
            prop: "RealQueryDate1",
            type: "datetime",
            format: "YYYY-MM-DD",
            valueFormat: "YYYY-MM-DD",
            disabled: true,
            rules: [
                {
                    trigger: "blur",
                    required: true,
                },
            ],
            span: 7
        },
        {
            label: "累计时段结束",
            prop: "QueryDate2",
            type: "datetime",
            format: "YYYY-MM-DD",
            valueFormat: "YYYY-MM-DD",
            disabled: true,
            rules: [
                {
                    trigger: "blur",
                    required: true,
                },
            ],
            span: 7
        },
        {
            label: "补货建议",
            prop: "buHuoJianYi",
            type: "select",
            dicData: [
                {
                    label: "全部",
                    value: 0
                },
                {
                    label: "紧急补货+补货",
                    value: 4
                },
                {
                    label: "紧急补货",
                    value: 2
                },
                {
                    label: "补货",
                    value: 3
                },
                {
                    label: "其他",
                    value: 1
                },
            ],
            props: {
                label: "label",
                value: "value",
            },
            // multiple: true, //多选
            // props: {
            //     label: "name",
            //     value: "id",
            // },
            // props: {
            //     api: "getbuhuojianyi@retail.po1.po1mnt007",
            //     radio: false,
            // },
            // component: "DroplistControl",
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择补货建议",
                    radio: false,
                    checkall: false,
                },
            ],
            span: 7
        },
        {
            label: "数据类型",
            prop: "UserType",
            type: "select",
            dicData: [
                {
                    label: "联营商",
                    value: "SUPP"
                },
                {
                    label: "联营款",
                    value: "GS"
                },
            ],
            props: {
                label: "label",
                value: "value",
            },
            rules: [
                {
                    trigger: "blur",
                    required: true,
                    message: "请选择数据类型",
                    radio: false,
                    checkall: false,
                },
            ],
            span: 7
        },
        {
            label: "款号/款字头",
            prop: "ItemNo",
            placeholder: "多个，分隔开",
            span: 10
        },


    ],
}